@echo off
echo Running update...
call npm run update
echo Building...
call npm run build
echo Adding changes to git...
git add .
echo Committing changes...
git commit -m "update"
echo Pushing to repository...
git push
echo Done.
